services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ../backend:/code
    depends_on:
      - database
  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ../frontend:/code/
    depends_on:
      - backend
